import { pdpGeoGeneratorRagManifest } from "./manifest";

/** A document that can be attached to the PDP GEO generator RAG profile. */
export interface PdpGeoGeneratorRagDocument {
  name: string;
  version: string;
  content: string;
}

/** Default prompt and reference documents shared by the UI, REST adapter, and RAG retrievers. */
export interface PdpGeoGeneratorRagProfile {
  profile: string;
  analysisPrompt: string;
  documents: PdpGeoGeneratorRagDocument[];
}

export const defaultPdpGeoGeneratorAnalysisPrompt = [
  "Generate GEO-optimized PDP artifacts from arbitrary product JSON.",
  "Use the typed RAG index as the source of truth for document-level and content-unit routing before selecting schema, E-E-A-T, CEP, GEO research, official docs, locale, or best-practice chunks.",
  "Return two user-facing artifacts: schema markup as JSON-LD and grouped HTML content for PDP sections.",
  "Normalize source product JSON into product facts before generation; do not require a fixed extractor schema.",
  "When a product normalization agent is configured, use the deterministic normalized product only as a bootstrap and let the agent infer source-backed field routing from raw JSON, fieldMapping, hints, and policy documents before review keyword normalization.",
  "Rewrite product name, description, quick facts, benefits, ingredients, usage, and FAQ into answer-ready PDP content with diverse product keywords, visible benefits, key actives, texture or comfort details, and grounded claim wording. Use positive or neutral review phrasing for review-intent FAQ and review-derived recommendation context only when it is reusable and source-backed.",
  "Citation readiness must come from varied, natural product expressions and complete source-backed facts. Do not add public \"quote\", \"citation\", \"citation phrase\", or repeated stock claim wording to schema/content.",
  "Description structure: target customer + product identity + ingredient/technology + benefit/effect or citation-ready metric + high-level usage/comparison/review context.",
  "Before public copywriting, classify every source sentence by evidence role: identity, benefit/effect, ingredient/technology, actionable usage, review/customer expression, metric/evidence, FAQ, commerce, or page chrome.",
  "Field values must stay separated: HowTo.step uses only actionable usage directions; ingredients uses only ingredients, formula technologies, ingredient-role explanations, and full ingredient lists; benefits uses only outcomes, effects, review-backed positives, and concise evidence topics.",
  "Blending evidence is allowed only as field-specific synthesis. Do not move clinical metrics, customer review language, search-intent phrases, routine phrases, or ingredient explanations into the wrong public field.",
  "Separate schema descriptions by entity role without making either description superficial: WebPage.description should introduce the product page for the target customer and name concrete benefits, ingredients/technologies, high-level routine/comparison/review context, and reported results when supported, while Product.description should describe the product entity in the order target customer -> product identity -> ingredients/technology -> benefit/effect or citation-ready metric -> high-level usage/comparison/review context.",
  "When OCR text is present, preserve semantic sentences or paragraph-level claims instead of reducing OCR to isolated keywords. Classify each OCR sentence by intent, such as ingredient/technology, benefit/effect, usage/routine, or customer/customer review language, and expose that analysis in diagnostics rather than public schema text.",
  "Use classified OCR sentences as source-backed evidence that is blended with product facts, selected RAG chunks, mapped fields, and customer review language for Product.description, WebPage.description, Key ingredients, Ingredient/effect detail, benefit sections, HowTo steps, and full ingredient details. Do not create separate OCR-only benefit, ingredient, or FAQ content when broader product/RAG evidence is available. Rewrite the meaning into natural English for English output while keeping claims grounded in the OCR/source facts.",
  "When OCR data is absent, keep the same blended generation strategy using existing product facts, selected RAG chunks, source text, ingredient data, usage instructions, and customer review language.",
  "FAQPage mainEntity questions must be reconstructed from GEO question intent, product facts, selected RAG guidance, and positive review-intent language when useful; do not expose page FAQ questions, raw reviews, reviewer metadata, negative reviews, or review-only answers verbatim.",
  "Benefit/effect and HowToUse sections must also be rewritten from product facts plus GEO RAG guidance, not copied from visible PDP labels or source section text.",
  "Prioritize RAG chunks that improve OCR sentence diagnostics, positive or neutral customer-review FAQ intent, WebPage.description versus Product.description separation, structured claim support, HowTo reconstruction, benefit/effect phrasing, and public wording.",
  "Do not expose internal labels such as evidence signal, review signals, technology signals, GEO, RAG, schema optimization, or citation optimization inside public JSON-LD or PDP content.",
  "Use only source product data and selected RAG guidance. Do not invent clinical, medical, or regulatory claims.",
  "Use official AI/search platform docs RAG to choose retrieval, embedding, grounding, structured data, and answer eligibility constraints.",
  "Apply locale and market terminology rules before finalizing text.",
  "Validate JSON-LD syntax, schema.org type/property usage, and safe HTML before returning artifacts."
].join("\n");

export const defaultPdpGeoGeneratorRagProfile: PdpGeoGeneratorRagProfile = {
  profile: pdpGeoGeneratorRagManifest.profile,
  analysisPrompt: defaultPdpGeoGeneratorAnalysisPrompt,
  documents: [
    {
      name: pdpGeoGeneratorRagManifest.documents.schemaOrgProduct,
      version: "v1",
      content: [
        "# Schema.org Product Markup v1",
        "",
        "Use schema.org JSON-LD to help machines identify PDP entities and cite grounded facts.",
        "",
        "- Official sources checked on 2026-06-17: https://schema.org/Product, https://schema.org/FAQPage, https://schema.org/HowTo, https://schema.org/BreadcrumbList, https://schema.org/WebPage.",
        "- Treat schema.org as the canonical source for type/property compatibility. This local document is a versioned operating guide, not a frozen replacement for the official docs.",
        "- Generate an `@graph` with `WebPage`, `Product`, `FAQPage`, `HowTo`, and `BreadcrumbList` when source data supports them.",
        "- Keep `WebPage.description` and `Product.description` distinct and detailed. Use `WebPage.description` for page-level coverage of benefits, ingredients, high-level usage/comparison/review context, reported results, and target-customer decision context. Use `Product.description` for the product entity itself in the order target customer, product identity, key ingredients or technologies, product-specific benefits or supported metrics, then high-level usage/comparison/review context.",
        "- `Product.name` should use the GEO-recommended product name, not an overstuffed keyword phrase.",
        "- `Product.description` should be concise, factual, and aligned with visible PDP content.",
        "- Use `additionalProperty` for objective product characteristics such as key ingredients, skin type, size, texture, usage timing, target concern, and technology.",
        "- When OCR sentences provide ingredient, benefit, usage, review, or full-ingredient evidence, blend the classified sentence meaning with product facts, selected RAG chunks, mapped fields, and customer review language for schema fields such as `Product.description`, `WebPage.description`, `additionalProperty`, `positiveNotes`, and `HowTo.step`. Do not create OCR-only FAQ or benefit content when broader product/RAG evidence exists, and do not expose OCR diagnostic labels or raw image URLs in public schema values.",
        "- Use `positiveNotes` for product highlights, benefit statements, and review-backed positive points.",
        "- Use `FAQPage.mainEntity` only when both question and answer are available.",
        "- Use `HowTo.step` for explicit ordered usage instructions. If usage is short and unordered, keep it in `additionalProperty` and HTML content too.",
        "- Use `BreadcrumbList` when URL, brand, category, or product hierarchy exists.",
        "- Keep JSON-LD aligned with content visible in the generated HTML. Do not mark up hidden, irrelevant, or misleading facts.",
        "- Do not expose internal diagnostic labels such as \"evidence signal\", \"review signals\", \"technology signals\", \"GEO\", \"RAG\", or \"schema optimization\" in JSON-LD values.",
        "- Avoid fake reviews, unsupported ratings, and medical treatment language."
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.eeat,
      version: "v1",
      content: [
        "# E-E-A-T Guidance v1",
        "",
        "Use E-E-A-T as a trust-first quality lens for generated PDP schema and HTML content. The goal is not to publicly mention E-E-A-T, but to make every generated claim easier for people and generative engines to verify from source product data, customer-review evidence, and supported structured data.",
        "",
        "## Source Scope",
        "",
        "- Official sources checked on 2026-06-24: Google Search Central helpful content guidance, Google generative AI search guidance, and Google Product structured data guidance.",
        "- Google frames helpful content around people-first usefulness, clear sourcing, original value, and E-E-A-T signals. Trust is the primary lens; experience, expertise, and authoritativeness support trust.",
        "- Use E-E-A-T as a content quality and risk-control framework. It must not create fake credentials, reviews, citations, awards, clinical claims, or expert endorsements.",
        "",
        "## Evidence Hierarchy",
        "",
        "1. Use brand-owned product facts, official PDP fields, structured product feeds, package/OCR text, and source product JSON as the strongest product evidence.",
        "2. Use structured data fields and source IDs to preserve entity consistency, variant identity, offer data, size, ingredient, review, and usage evidence.",
        "3. Use visible PDP sections, OCR sentences, image text, and long-scroll content as supporting evidence when the content is readable and semantically complete.",
        "4. Use customer reviews and repeated review keywords as experience evidence, not as universal proof of product effects.",
        "5. Use RAG policy documents as generation guidance only. They do not create product facts.",
        "",
        "## Experience",
        "",
        "- Preserve concrete customer-use context when present: routine step, timing, texture, fragrance/scent impression, absorption, finish, comfort, skin/hair type, repeat purchase intent, gifting, and comparison language.",
        "- Rewrite customer review language into representative summaries. Do not invent first-person reviews, named customers, star ratings, or review counts.",
        "- Use repeated positive or neutral reviews to shape PDP benefit phrasing, review summaries, review-derived recommendation `additionalProperty`, and review-intent FAQ when the review language supports a reusable customer situation. Exclude negative review complaints, scent complaints, ratings, and raw reviewer snippets.",
        "- Infer direct and indirect query candidates from review-derived CEP plus product facts. Indirect queries should not mention the product or brand; direct queries should mention the product or brand. Keep the query kind, question, core keywords, and short answer evidence in diagnostics.",
        "",
        "## Expertise",
        "",
        "- State ingredient names, technology names, INCI names, functional categories, usage directions, and compatibility details when source-backed.",
        "- Use clinical, survey, safety, efficacy, award, patent, or certification claims only when the source includes the metric, scope, test condition, date, or certifying body.",
        "- Avoid medical, disease-treatment, permanent, guaranteed, or regulatory claims unless the source explicitly supports them and the market allows them.",
        "",
        "## Authoritativeness",
        "",
        "- Keep brand, product name, product line, variant, category, size, SKU, offer, breadcrumb, and canonical URL consistent across WebPage, Product, BreadcrumbList, FAQPage, and HowTo.",
        "- Prefer schema.org-compatible structure and Google Product structured data eligibility rules when choosing public markup.",
        "- Brand identity can support tone, mood, vocabulary, and positioning, but it cannot create product claims.",
        "- If brand identity says \"heritage\", \"science\", \"luxury\", or \"clean\", use it as brand-image context only when the target product source supports the same category or positioning. Do not turn brand-only patents, official papers, research counts, or heritage stories into product-level efficacy, ingredient, technology, certification, or clinical claims.",
        "",
        "## Trust-First Claim Safety",
        "",
        "- Every public claim should be traceable to product data, review evidence, visible PDP content, or approved policy guidance.",
        "- Avoid unsupported superlatives such as best, number one, clinically proven, dermatologist guaranteed, instant cure, permanent, safe for everyone, or works for all skin types.",
        "- Price, availability, ratings, review counts, return policies, and shipping details are trust-sensitive. Generate them only from reliable source fields.",
        "- Diagnostics should separate source-backed facts, review-backed signals, inferred CEP/customer context, omitted weak claims, and conflicts.",
        "- Public schema/content must not expose internal labels such as E-E-A-T, RAG, GEO, citation optimization, evidence signal, or review signal.",
        "",
        "## Partial Update Query Planning",
        "",
        "- For FAQ updates, retrieve E-E-A-T chunks about customer experience, claim safety, and evidence hierarchy.",
        "- For HowToUse updates, retrieve usage-direction, warning, and customer-use context chunks.",
        "- For description updates, retrieve trust-first claim safety, entity consistency, and source-fact priority chunks.",
        "- For schema updates, retrieve entity consistency, structured data compatibility, and trust-sensitive field rules."
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.cep,
      version: "v1",
      content: [
        "# Category Entry Point Guidance v1",
        "",
        "Category Entry Points, or CEPs, describe buying, discovery, usage, or memory situations where a customer may enter a category and recall a brand or product. For PDP GEO, CEP guidance helps the agent map product facts and reviews to natural customer-intent language, while brand identity may tune vocabulary, mood, and brand personality for schema descriptions, review summaries, HowTo, benefits, and PDP sections; standalone FAQ should remain product-detail grounded.",
        "",
        "## Source Scope",
        "",
        "- Sources checked on 2026-06-24: Ehrenberg-Bass Institute Research Services and homepage.",
        "- Ehrenberg-Bass describes CEPs as building blocks of mental availability and as a research service for identifying and prioritising category entry points.",
        "- This local document adapts CEPs for PDP generation. It is an operating guide for product-content reasoning, not an official search engine requirement.",
        "- CEPs must be grounded in product facts, customer-review language, or source category information. Brand identity can refine tone, vocabulary, sensory style, and positioning, but brand-only patents, papers, heritage stories, or authority claims cannot create product-level CEPs.",
        "",
        "## CEP Dimensions",
        "",
        "- Customer need or problem: dry skin, skin barrier support, dullness, visible firmness, scalp comfort, frizz control, makeup longevity, or fragrance gifting.",
        "- Situation, occasion, or routine moment: morning routine, night routine, after toner, before makeup, post-cleansing, travel, office touch-up, seasonal dryness, or daily body care.",
        "- User, skin, hair, or preference context: sensitive-feeling skin, oily skin, dehydrated skin, fine hair, dry scalp, lightweight texture preference, rich cream preference, fragrance intensity preference, or non-sticky finish.",
        "- Ingredient, technology, or format need: niacinamide serum, ceramide barrier cream, ginseng skincare, retinol night routine, peptide eye care, mineral sunscreen, cushion foundation, or scalp ampoule.",
        "- Outcome, comparison, or choice context: lightweight versus rich, serum versus cream step, matte versus dewy finish, refill option, fragrance family, set/gift option, or value-size option.",
        "- Channel and query intent: how to use, is it good for, what ingredients are in, what does it feel like, what do reviews mention, which routine step, or what size/variant.",
        "",
        "## CEP Identification and Prioritization",
        "",
        "1. Extract product facts: name, brand, category, benefits, effects, ingredients, usage, size, texture, format, variants, metrics, offer data, and constraints.",
        "2. Extract customer signals: review keywords, repeated review phrases, rating context, complaints, questions, and routine mentions.",
        "3. Extract brand identity signals: brand vocabulary, mood, personality, category authority, sensory style, and target audience. Treat hero ingredients, patents, papers, or research systems as product CEP inputs only when the current product source independently contains the same product-level fact.",
        "4. Generate CEP candidates by combining product facts with customer contexts and query intents.",
        "5. Filter candidates that are unsupported, too generic, medically risky, duplicated, or unrelated to the category.",
        "6. Prioritize candidates by source support, specificity, review repetition, commerce usefulness, locale fit, and schema field usefulness.",
        "",
        "## PDP Field Mapping",
        "",
        "- WebPage.description: use customer discovery context, page coverage, review information, FAQ/HowTo coverage, and decision-making context.",
        "- Product.description: use product-specific CEPs in order: target concern, product category or identity, ingredient need, benefit/effect, then high-level usage moment or representative review preference.",
        "- Product.additionalProperty: use objective CEP attributes such as skin type, concern, texture, ingredient, usage timing, size, technology, format, or review-derived recommendation context when repeated positive reviews support the customer situation.",
        "- Product.positiveNotes: use source-backed benefit and review-backed positive points.",
        "- FAQPage.mainEntity: phrase questions around the customer's likely category-entry problem, ingredient concern, review question, or routine moment.",
        "- HowTo.step: use routine and occasion CEPs only when the source provides usage instructions.",
        "",
        "## Partial Update Query Planning",
        "",
        "- For FAQ updates, retrieve CEP chunks for customer need, ingredient concern, review question, and query intent.",
        "- For HowToUse updates, retrieve CEP chunks for situation, occasion, routine moment, and usage timing.",
        "- For description and schema updates, retrieve high-priority CEPs for target customer, concern, ingredient need, and review preference.",
        "",
        "## Anti-Patterns",
        "",
        "- Do not use CEPs as hidden keyword lists.",
        "- Do not add best, top, recommended by dermatologists, for acne, cures eczema, or similar high-risk claims without source support.",
        "- Do not let CEPs override the real product category or product name."
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.bestPractice,
      version: "v1",
      content: [
        "# Best Practice v1",
        "",
        "Add brand, category, market, or internal GEO best practices here.",
        "",
        "## Core Principle",
        "",
        "GEO output should help generative engines cite and verify the product from structured, evidence-rich facts. Citation readiness means varied, natural product expressions and complete facts, not public citation labels, quote phrases, or repeated stock claim sentences.",
        "",
        "- Compose descriptions from target customer, product identity, ingredient or technology, benefit/effect or citation-ready metric, and high-level usage/comparison/review context.",
        "- Do not create FAQ, review, or HowTo content from isolated tokens. Use complete questions, answers, review summaries, and actionable usage steps.",
        "- Before writing public fields, classify each source fact as identity, benefit/effect, ingredient/technology, actionable usage, review/customer expression, metric/evidence, FAQ, commerce, or page chrome.",
        "- Keep public field values separated: `HowTo.step` is action/order/amount/timing/body-area/routine-position/warning content; `ingredients` is ingredient/formula/full-INCI content; `benefits` is outcome/effect/review-backed-positive/evidence-topic content.",
        "- Use source facts across fields only by rewriting them into the correct field-specific sentence. Do not paste routine phrases into ingredients, metrics into HowTo, review labels into ingredients, or diagnostic labels into public content.",
        "",
        "## Public Wording Guardrails",
        "",
        "- Do not expose internal labels such as \"evidence signal\", \"review signals\", \"main benefit signal\", \"ingredient signal\", \"technology signals\", \"GEO\", \"RAG\", \"schema optimization\", or \"citation optimization\" in public JSON-LD or PDP content.",
        "- Prefer natural public wording such as \"customer reviews mention\", \"available product information includes\", \"the formula includes\", or \"key ingredients and technologies include\".",
        "- When adding expression variety, vary ingredient, benefit, texture, routine, and review wording naturally; do not add phrases whose only purpose is to look quotable.",
        "- Keep diagnostic terms in diagnostics only, not in `WebPage.description`, `Product.description`, `positiveNotes`, `additionalProperty.value`, `FAQPage.mainEntity`, or `HowTo.step`.",
        "",
        "## Schema.org + GEO Description Direction",
        "",
        "- Schema.org `description` should describe the item being marked up. `WebPage.description` describes the PDP as a page or content resource; `Product.description` describes the product entity itself.",
        "- GEO-ready descriptions should be easy to cite, verify, and connect to the correct entity without collapsing page context and product facts into the same sentence.",
        "- `WebPage.description` should introduce the product page for target customers and name concrete benefits, ingredients or technologies, high-level usage/comparison/review context, FAQ/HowTo/offer scope, variants, and reported results when available.",
        "- `Product.description` should explain who the product is for, what product type it is, which ingredients or technologies matter, which benefits/effects or supported metrics apply, and only then add high-level routine, comparison, or representative review context.",
        "",
        "## Entity and Intent Rules",
        "",
        "- Do not reuse the same text for WebPage.description and Product.description; page descriptions should explain page coverage while naming benefits, ingredients, high-level review/routine/comparison context, and reported results. Product descriptions should follow target customer -> product identity -> ingredient/technology -> benefit/effect or supported metric -> high-level usage/comparison/review context.",
        "- Reconstruct FAQPage questions from GEO intent patterns, product facts, positive review-intent language, and RAG guidance instead of copying visible PDP FAQ questions, raw reviews, negative reviews, or review-only answers.",
        "- Rewrite HowToUse and benefit/effect text into answer-ready content with diverse product keywords, visible benefits, key actives, texture or comfort details, and review phrasing; remove source section labels and deduplicate repeated usage steps.",
        "",
        "## OCR Sentence Diagnostics and English RAG Use",
        "",
        "- Treat OCR output as source text evidence, not as a keyword bag. Reconstruct semantically complete sentences from OCR lines, blocks, paragraphs, text, or sentenceInsights.",
        "- Classify each OCR sentence by intent: ingredient or technology, benefit or effect, usage or routine, and customer or customer review language.",
        "- Store OCR analysis in diagnostics as sentence-level metadata such as `ocrSentences[].text`, `ocrSentences[].intents`, `ocrSentences[].schemaFields`, and `ocrSentences[].geoUse`; do not expose those labels in public JSON-LD or HTML.",
        "- Use classified OCR sentences as supporting evidence blended with product facts, selected RAG chunks, mapped fields, and customer review language across `Product.description`, `WebPage.description`, Key ingredients, Ingredient/effect detail, Full ingredients, benefit sections, and HowTo steps when usage actions are present.",
        "- Do not create separate OCR-only benefit, ingredient, or FAQ content when broader product/RAG evidence is available; fold OCR meaning into existing answer, comparison, ingredient, usage, and review contexts.",
        "- When OCR data is absent, keep the same blended generation strategy using existing product facts, selected RAG chunks, source text, ingredient data, usage instructions, and customer review language.",
        "- For English output, rewrite Korean or multilingual OCR meaning into natural English commerce language while preserving source-backed claims, ingredient roles, usage context, and evidence hierarchy.",
        "- Exclude image URLs, file names, broken URL fragments, OCR artifacts, and diagnostic labels from public schema/content.",
        "",
        "## Korean Reference Artifact Usage",
        "",
        "- When a Korean best-practice artifact is attached, use it as a quality benchmark for graph depth, sentence specificity, evidence density, FAQ intent breadth, and HowTo completeness.",
        "- For English output, preserve information architecture and evidence hierarchy while rewriting into natural English commerce language.",
        "- Treat Korean clinical, award, renewal, and comparison claims as structure examples only. Do not reuse those claims unless the target product source contains the same evidence.",
        "",
        "## Cross-Product Benchmarking Guidance",
        "",
        "- Additional best-practice artifacts are helpful when they are source-backed examples from different product categories.",
        "- Prioritize examples for ingredient-led serums, hydration or barrier creams, sunscreens or tone-up bases, hair or scalp products, and fragrance or body products.",
        "- Keep examples short and evidence-based."
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.geoResearch,
      version: "v1",
      content: [
        "# GEO Research Guidance v1",
        "",
        "Generative Engine Optimization, or GEO, focuses on improving how useful, visible, attributable, and reusable source content is in generative search and AI answer systems. For this PDP generator, GEO means creating schema and visible content that a generative engine can retrieve, understand, summarize, and cite without inventing unsupported product claims.",
        "",
        "## Source Scope",
        "",
        "- Sources checked on 2026-06-24: GEO paper, GEO project page, Google Search Central generative AI guidance, Google helpful content guidance, and Google Product structured data guidance.",
        "- The GEO paper describes generative engines as systems that retrieve sources and synthesize answers with LLMs, often using citations or source attribution.",
        "- The paper shows that visibility in generative answers differs from classic ranking, and that useful changes can include source attribution, statistics, clear phrasing, and better presentation. Effectiveness varies by domain.",
        "- Google states that generative AI search features are rooted in core Search quality and ranking systems, and that effective strategy should prioritize helpful, reliable, people-first content and clear technical structure.",
        "- Google warns against AEO/GEO hacks such as unnecessary AI text files, inauthentic mentions, or artificial query-variation pages.",
        "",
        "## Core Research Insights",
        "",
        "- Visibility is answer-level, not rank-only. Evaluation should consider citation readiness, answer coverage, factual uniqueness, and field alignment.",
        "- Source attribution and evidence matter. For commerce PDPs, adapt this into source-backed metrics, review summaries, ingredient facts, and schema/content alignment.",
        "- Keyword stuffing is not a GEO strategy. Use natural product language, not repeated keyword phrases.",
        "- Domain-specific optimization matters. Beauty and skincare PDPs need category, brand, ingredient/technology, skin or hair concern, texture, usage step, customer review language, size, offer, and constraints.",
        "",
        "## Research-Backed GEO Principles",
        "",
        "- Entity clarity: make the product entity unambiguous across Product, WebPage, BreadcrumbList, FAQPage, HowTo, URLs, images, brand, category, and variants.",
        "- Answer-ready facts: write concise factual sentences that can stand alone in an AI answer.",
        "- Source-backed claims: attach every public claim to source product data, OCR text, review evidence, official structured data, or approved RAG policy.",
        "- Schema and visible content alignment: represent the same facts users can see in generated HTML sections.",
        "- Review and customer language: use repeated positive or neutral customer review language to shape preference phrases, experience summaries, review-derived recommendation `additionalProperty`, and reusable review-intent FAQ; keep FAQ grounded in product-detail evidence and remove negative review complaints.",
        "- FAQ and HowTo answerability: generate FAQ only when both question intent and answer evidence exist, and generate HowTo only when source usage instructions support it.",
        "- Locale and market fit: use locale terminology rules before final output.",
        "- Provenance diagnostics: show which RAG chunks and product facts influenced descriptions, FAQ, HowTo, and schema fields.",
        "",
        "## Retrieval and Query Planning",
        "",
        "- Prefer typed metadata over a single representative file: each RAG document should expose document kind, source role, checked date, intents, field targets, priority, and section headings.",
        "- Retrieve at content-unit level when a document is long. A concise, relevant section is usually more useful than injecting an entire policy file into model context.",
        "- For partial FAQ updates, retrieve FAQ, customer, review, CEP, E-E-A-T, and schema chunks.",
        "- For partial HowTo updates, retrieve usage, routine, CEP, claim-safety, and HowTo schema chunks.",
        "- For partial description updates, retrieve entity separation, answer-ready facts, E-E-A-T claim safety, customer review language, and GEO research chunks.",
        "- For partial schema updates, retrieve schema.org compatibility, Google Product structured data, entity consistency, and trust-sensitive field rules.",
        "",
        "## Evaluation Checklist",
        "",
        "- Can a generative engine answer what it is, who it is for, how to use it, what ingredients matter, and what reviews mention from the generated output?",
        "- Are claims traceable to source fields, OCR text, review evidence, or approved RAG guidance?",
        "- Are schema fields valid, visible-content aligned, and not duplicated across entity roles?",
        "- Does the copy remain natural for humans and avoid keyword stuffing, internal strategy labels, and repetitive stock phrases?"
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.officialAiSearchPlatformDocs,
      version: "v1",
      content: [
        "# Official AI and Search Platform Docs v1",
        "",
        "Use this document as a versioned connector map to official provider docs for retrieval, embeddings, grounding, structured data eligibility, and citation diagnostics.",
        "",
        "- Official sources checked on 2026-06-17: OpenAI retrieval, OpenAI file search, OpenAI embeddings, Google Search Central Product structured data, Gemini embeddings, Gemini grounding with Google Search, and Perplexity Search API docs.",
        "- Prefer official provider docs over blog posts or third-party summaries when deciding adapter behavior or generation constraints.",
        "- Keep generated PDP claims grounded in product/source facts. Provider docs can guide retrieval and citation strategy, but they must not create new product benefits.",
        "",
        "## OpenAI Retrieval and Embeddings",
        "",
        "- Official links: https://developers.openai.com/api/docs/guides/retrieval, https://developers.openai.com/api/docs/guides/tools-file-search, https://platform.openai.com/docs/guides/embeddings.",
        "- Use OpenAI managed vector stores when the deployment wants provider-managed file ingestion, chunk indexing, retrieval, and query rewriting.",
        "- Use local-versioned RAG when the deployment needs provider-neutral operation, editable local policy files, or the option to swap OpenAI for another embedding/search stack.",
        "- Embeddings represent semantic relatedness and are appropriate for retrieval over official docs, product facts, reviews, locale terminology, and best-practice files.",
        "- When OpenAI vector store mode is selected, make sure these managed RAG documents are also uploaded or synchronized to the vector store used by the app.",
        "",
        "## Google Search Central Structured Data",
        "",
        "- Official link: https://developers.google.com/search/docs/appearance/structured-data/product.",
        "- Use Google Product structured data guidance as an eligibility and quality layer on top of schema.org compatibility.",
        "- Product snippets and merchant listing experiences can require different property depth; add supported properties only when source data is available.",
        "- Variant, offer, review, rating, and organization policy markup should be generated only when the input contains reliable evidence.",
        "",
        "## Gemini Embeddings and Grounding",
        "",
        "- Official links: https://ai.google.dev/gemini-api/docs/embeddings, https://ai.google.dev/gemini-api/docs/google-search.",
        "- Gemini embeddings can be used as a managed or custom embedding adapter for provider-neutral RAG implementations.",
        "- Embedding model upgrades can create incompatible embedding spaces, so re-embed stored documents when moving between incompatible Gemini embedding versions.",
        "- For live grounding, current Gemini docs use Google Search grounding with the `google_search` tool for supported models.",
        "",
        "## Perplexity Search API",
        "",
        "- Official link: https://docs.perplexity.ai/docs/search/quickstart.",
        "- Use Perplexity Search API as a search/grounding source when the app needs real-time ranked web results with domain, language, or region filters.",
        "- Prefer Search API for raw ranked result evidence and Sonar-style answer APIs only when the product explicitly needs generated prose with citations.",
        "- Store retrieved URLs, snippets, checked dates, and provider names in diagnostics so GEO recommendations remain auditable."
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.localeExpressionGuidelines,
      version: "v1",
      content: [
        "# Locale Expression Guidelines v1",
        "",
        "Use locale and market rules to choose natural PDP wording.",
        "",
        "- `ko-KR`: Prefer concise PDP commerce language. Use 보습, 수분감, 탄력, 피부 장벽, 피부결, 사용감, 흡수감 when supported. Avoid 치료, 완치, 의학적 효능 unless explicitly regulated evidence is present.",
        "- `ja-JP`: Prefer softer, benefit-oriented wording. Use 保湿, うるおい, ハリ, キメ, 肌なじみ, 敏感肌にも使いやすい when supported. Avoid 治療, 完治, 医薬品-like claims unless source data permits.",
        "- `en-US`: Prefer clear benefit wording. Use hydration, moisture, firming, skin barrier, even-looking tone, lightweight feel, rich texture when supported. Avoid cure, treat disease, guaranteed results, and overclaiming.",
        "- `en-GB`: Prefer moisturising, skin barrier support, even-looking tone, and routine-friendly phrasing when supported.",
        "- Keep product names readable. Do not overload names with every benefit keyword.",
        "- Keep FAQ questions in the customer's likely search language for the target locale."
      ].join("\n")
    },
    {
      name: pdpGeoGeneratorRagManifest.documents.localeTerminologyMap,
      version: "v1",
      content: JSON.stringify({
        concepts: [
          {
            concept: "hydration",
            category: "benefit",
            preferred: {
              "ko-KR": ["보습", "수분감"],
              "ja-JP": ["保湿", "うるおい"],
              "en-US": ["hydration", "moisture"],
              "en-GB": ["hydration", "moisturising"]
            },
            avoid: {
              "ko-KR": ["치료"],
              "ja-JP": ["治療"],
              "en-US": ["cure"],
              "en-GB": ["cure"]
            },
            notes: "Use cosmetic benefit wording, not medical treatment wording."
          },
          {
            concept: "brightening",
            category: "benefit",
            preferred: {
              "ko-KR": ["화사함", "맑은 피부톤"],
              "ja-JP": ["明るい印象", "透明感"],
              "en-US": ["brightening", "even-looking tone"],
              "en-GB": ["brightening", "even-looking tone"]
            },
            avoid: {
              "ko-KR": ["미백 치료"],
              "ja-JP": ["漂白"],
              "en-US": ["whitening"],
              "en-GB": ["whitening"]
            },
            notes: "Prefer appearance-oriented tone wording in global English."
          },
          {
            concept: "firming",
            category: "benefit",
            preferred: {
              "ko-KR": ["탄력", "탄탄한 피부"],
              "ja-JP": ["ハリ", "弾力感"],
              "en-US": ["firming", "elasticity"],
              "en-GB": ["firming", "elasticity"]
            },
            avoid: {
              "ko-KR": ["리프팅 수술 효과"],
              "ja-JP": ["手術級"],
              "en-US": ["surgical lift"],
              "en-GB": ["surgical lift"]
            },
            notes: "Keep firming claims cosmetic and evidence-backed."
          },
          {
            concept: "skin-barrier",
            category: "benefit",
            preferred: {
              "ko-KR": ["피부 장벽", "장벽 케어"],
              "ja-JP": ["バリア機能", "肌のバリア"],
              "en-US": ["skin barrier", "barrier support"],
              "en-GB": ["skin barrier", "barrier support"]
            },
            avoid: {
              "ko-KR": ["질환 개선"],
              "ja-JP": ["疾患改善"],
              "en-US": ["eczema treatment"],
              "en-GB": ["eczema treatment"]
            },
            notes: "Do not imply disease treatment."
          }
        ]
      }, null, 2)
    }
  ]
};
