/**
 * Generates the inline bootstrap fallback module from the committed managed
 * RAG markdown/JSON corpus and the analysis prompt file.
 *
 * `src/rag/default-profile.ts` only needs a fallback when a managed file is
 * missing on disk (see profile.ts); this script keeps that fallback a
 * byte-for-byte copy of the committed corpus instead of a hand-maintained,
 * drift-prone abridgement. The drift CI test
 * (`tests/rag-profile.test.ts` — "keeps the inline fallback corpus identical
 * to the committed markdown corpus") fails if the generated file falls out
 * of sync with the corpus.
 *
 * Usage:
 *   npm run rag:generate-fallback
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { pdpGeoGeneratorRagManifest } from "../src/rag/manifest";

const ragDirectory = join(dirname(fileURLToPath(import.meta.url)), "../src/rag");
const outputPath = join(ragDirectory, "default-profile-fallback.generated.ts");

async function main(): Promise<void> {
  const documentNames = Object.values(pdpGeoGeneratorRagManifest.documents);
  const entries: string[] = [];
  for (const name of documentNames) {
    const content = await readFile(join(ragDirectory, name), "utf8");
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)}`);
  }
  const analysisPrompt = await readFile(join(ragDirectory, pdpGeoGeneratorRagManifest.analysisPrompt), "utf8");
  const banner = "// AUTO-GENERATED by scripts/generate-default-profile-fallback.ts — do not edit by hand.\n"
    + "// Regenerate with: npm run rag:generate-fallback\n";
  const body = `${banner}export const generatedAnalysisPromptFallback = ${JSON.stringify(analysisPrompt)};\n\n`
    + `export const generatedRagFallbackDocuments: Record<string, string> = {\n${entries.join(",\n")}\n};\n`;
  await writeFile(outputPath, body, "utf8");
  console.log(`generated ${outputPath} with ${documentNames.length} documents`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
