"""Shared deterministic wording and source-evidence contracts."""

from .analysis_label import (
    CONSUMER_ASSESSMENT_LABEL,
    INTERNAL_ANALYSIS_LABEL_ALTERNATION,
    LABEL_AS_NOUN_PHRASE_SUFFIX,
    PRIMARY_ANALYSIS_LABEL,
    PUBLISHABLE_KOREAN_RESULT_PHRASE,
    REPORTING_LEAD_LABEL_ALTERNATION,
    has_analysis_label_artifact,
    is_analysis_label_prefixed,
    match_assessment_context_label,
)
from .certification import (
    contains_serialized_metadata,
    is_quantified_clinical_result_sentence,
    restates_typed_field_as_raw_transcription,
    select_atomic_functional_certification_values,
)
from .enumeration import (
    PROSE_COORDINATE_ITEM_LIMIT,
    has_unpredicated_enumeration,
    unpredicated_enumeration_sentence,
)
from .image_source import is_publishable_image_url
from .ingredient_vocabulary import (
    IngredientSurfaceRule,
    brand_ingredient_surface_rules,
    canonical_ingredient_surface,
    generic_ingredient_surface_rules,
    ingredient_substance_key,
    ingredient_surface_rules,
    ingredient_surfaces_present_in,
)
from .metric_statement import is_structured_atomic_metric_claim
from .product_type import PdpGeoLocale, localize_product_type_for_locale, product_type_from_name
from .sentence_form import (
    is_korean_complete_sentence,
    is_korean_polite_sentence_ending,
    is_separator_joined_list,
    korean_object_slot_phrase,
    korean_phrase_head_token,
)
from .usage import (
    clean_usage_text,
    has_actionable_application_verb,
    has_actionable_application_verb_without_generic_apply,
    has_concrete_korean_usage_action,
    has_context_free_figure_run,
    has_descriptive_application_frame,
    has_korean_instruction_verb,
    has_procedure_action_cue,
    has_routine_placement_cue,
    has_sensory_evaluation_frame,
    has_wash_action_cue,
    is_concrete_usage_action,
    is_procedural_usage_instruction,
    is_raw_page_text_block,
    is_safety_or_test_claim_usage,
    is_stitched_marketing_page_dump,
    usage_description_signal_score,
    usage_procedure_signal_score,
)

__all__ = [
    "CONSUMER_ASSESSMENT_LABEL",
    "INTERNAL_ANALYSIS_LABEL_ALTERNATION",
    "LABEL_AS_NOUN_PHRASE_SUFFIX",
    "PUBLISHABLE_KOREAN_RESULT_PHRASE",
    "PRIMARY_ANALYSIS_LABEL",
    "PROSE_COORDINATE_ITEM_LIMIT",
    "PdpGeoLocale",
    "REPORTING_LEAD_LABEL_ALTERNATION",
    "IngredientSurfaceRule",
    "brand_ingredient_surface_rules",
    "canonical_ingredient_surface",
    "clean_usage_text",
    "contains_serialized_metadata",
    "generic_ingredient_surface_rules",
    "has_actionable_application_verb",
    "has_actionable_application_verb_without_generic_apply",
    "has_analysis_label_artifact",
    "has_concrete_korean_usage_action",
    "has_context_free_figure_run",
    "has_descriptive_application_frame",
    "has_korean_instruction_verb",
    "has_procedure_action_cue",
    "has_routine_placement_cue",
    "has_sensory_evaluation_frame",
    "has_unpredicated_enumeration",
    "has_wash_action_cue",
    "ingredient_substance_key",
    "ingredient_surface_rules",
    "ingredient_surfaces_present_in",
    "is_analysis_label_prefixed",
    "is_concrete_usage_action",
    "is_korean_complete_sentence",
    "is_korean_polite_sentence_ending",
    "is_procedural_usage_instruction",
    "is_publishable_image_url",
    "is_quantified_clinical_result_sentence",
    "is_raw_page_text_block",
    "is_safety_or_test_claim_usage",
    "is_separator_joined_list",
    "is_stitched_marketing_page_dump",
    "is_structured_atomic_metric_claim",
    "korean_object_slot_phrase",
    "korean_phrase_head_token",
    "localize_product_type_for_locale",
    "match_assessment_context_label",
    "product_type_from_name",
    "restates_typed_field_as_raw_transcription",
    "select_atomic_functional_certification_values",
    "unpredicated_enumeration_sentence",
    "usage_description_signal_score",
    "usage_procedure_signal_score",
]
